### ISSUE TITLE
WP 3.3: With the latest build of Magic Fields, the add post type screen is all messed up

### ISSUE THREAD

**Issue by EivindFS** [magic-fields-team/Magic-Fields-2#100]
Hi!

This is what it looks like
http://files.sigarett.com/repository/mf-bug.png

This is true on two sites I have tested it on, so it must be a general bug.

When can I expect Magic Fields to work with Wordpress 3.3?

Cheers,
Eivind

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
