### ISSUE TITLE
Feature request: Hierarchical custom taxonomy slugs

### ISSUE THREAD

**Issue by ptrm** [magic-fields-team/Magic-Fields-2#102]
Since 3.1, Wordpress support hierarchical taxonomy slugs, meaning hiearchical taxonomies can get proper urls. (e.g. taxonomy-name/category/sub-category/). I manually changed the code to fit my needs, though it would be great if there was an option for that in the settings. I hope the 3.0 non-compatiblity can somehow be managed cleanly.

If anyone feels a need to do that too, the line to change is inside `mf_register.php` (line 110):

```
      if($option['rewrite'] && $option['rewrite_slug'])
        $option['rewrite'] = array( 'slug' => $option['rewrite_slug'], 'hierarchical' => true );
```

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
