### ISSUE TITLE
Unable to insert image into Post using Gallery, Media Library

### ISSUE THREAD

**Issue by ccalleo** [magic-fields-team/Magic-Fields-2#109]
I'm running MagicFields 2, Wordpress 3.2. I've turned off all plugins except for askimet. When I try simply to insert an image into a post by going Upload/Insert -- Media Library -- Show -- Insert into field nothing happens. It gets stuck. 

When I turn off the Magic Fields Plugin, inserting an image works again. No other plugins are running.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
