### ISSUE TITLE
Visual editing brakes with qTranslate plugin enabled

### ISSUE THREAD

**Issue by gabor-udvari** [magic-fields-team/Magic-Fields-2#120]
If both Magic Fields 2 and [qTranslate](http://wordpress.org/extend/plugins/qtranslate/) plugins are enabled saving doesn't work in visual mode. It gives a feedback that the post is updated, but the main text remains the same. If you switch to HTML mode before saving everything is fine. MF2 and qTranslate alone work as expected, but if both are enabled this bug comes up. This could be related just to qTranslate itself, since users already [reported something similar](http://wordpress.org/support/topic/plugin-qtranslate-latest-version-destroying-data-horrifying).

Versions: qTranslate 2.5.28, Magic Fields 2 latest git, Wordpress 3.3.1, clean install

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
