### ISSUE TITLE
Breadcrumbs not working with MF2

### ISSUE THREAD

**Issue by boff2000** [magic-fields-team/Magic-Fields-2#124]
I have a number of project pages whose permalinks display as `www.sitename.com/projects/project-name/` however my Yoast Breadcrumbs display `Home - Blog - Project Name`.

I can think of a few reason why it's not working in general.. but I'm not sure why it's displaying Blog, since I've set the post-type's capability type to 'page'. EDIT: I can change Blog to something else in the Yoast Breadcrumbs settings. But still this doesn't fix the issue. What if there were Projects, Videos and Products (or something)

I've also tried Really Simple Breadcrumbs, and that displays `Home - - Project Name`

Anyone had any success with breadcrumbs + MF2? Any wordarounds/fixes?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
