### ISSUE TITLE
get() outside the loop not working

### ISSUE THREAD

**Issue by alexmacrae** [magic-fields-team/Magic-Fields-2#125]
According to http://wiki.magicfields.org/doku.php?id=front-end_functions#get this is meant to work. I'm trying what the wiki suggests to no avail:

```
echo get('field_name', 1, 1, 1, 182);
// and
echo get('field_name', 1, 1, true, 182);
// get nothing
```

What's strange is that get_image() **does** fetch an image from a specified $page_id

```
echo get_image('image', 1, 1, 1, 182);
```

What am I doing wrong? Or is this a bug?

**Comment by kennethz3** [comment]
Worked for me. Thanks @gabor-udvari
