### ISSUE TITLE
Can anyone give me sample frontend posting form for Magic fields 2.x?

### ISSUE THREAD

**Issue by mistergiri** [magic-fields-team/Magic-Fields-2#126]
My posts completely using magic fields 2.0

I don't want my users to use backend.  So @magic-fields-team  can you give us sample php template to use it in front end.  
It will be very useful to people like me 

For example my post editor has the following fields.

```
Title
Description

Duplicate type group 
Image Title (textbox)
Image Description (Markdown editor)
Image (image)

Notes (Markdown editor) - Duplicate type

Comments  (Markdown editor)

```

So can anyone give me sample frontend posting form?

Thanks

PS: I'm using magic fields for almost more than 1 year. I contributed here by opening many bug reports. You can see some threads opened by me here are more than 8 months old.
Magic fields 2.x satisfying all my needs. But still i couldn't able to launch my website. The point is my some of my old wordpress websites hacked many times. So i'm still afraid to let my users use wp-admin/backend.  
In the beginning i was very keen in using magic fields. But after 8 months of waiting my interest fading everyday.
So can anyone save me by giving some sample code especially for that duplicate type and image upload function.
If you can spend few minutes to write the code i would be really thankful to you @gabor-udvari  Can you?

If anyone looking for this feature like me please comment here. Thanks

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
