### ISSUE TITLE
Feature request - Nested groups

### ISSUE THREAD

**Issue by mistergiri** [magic-fields-team/Magic-Fields-2#13]
I was wondering would it be possible to add nested groups feature. Magic fields 2 has all the features except that nested groups. Or its already available there? Am i missing something.

This is what i'm trying to implement.

Main group: Movies
Group has some sub groups like Information,imdb information and other groups. Each of these sub groups has some fields.

Now is it possible to duplicate the main movies group?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
