### ISSUE TITLE
Populating the wordpress exerpt with a different field from the editor.

### ISSUE THREAD

**Issue by bonzodese** [magic-fields-team/Magic-Fields-2#135]
I've a Post Type which the only supports checked and active are "title" and "revisions".
As I'm not using the "editor" (at least I guess this is the reason) if I run a wordpress search, and intercept this Post Type, the results have no exerpt but only a title. How can I have the exerpt populated with a different and custom multiline filed from the editor?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
