### ISSUE TITLE
Checkbox Data Still in Database

### ISSUE THREAD

**Issue by mehmetgultekin** [magic-fields-team/Magic-Fields-2#145]
Hi,

First of all thank you for great plugin.

I realized a problem today. If i create a checkbox list field and if i check one of the values and save, then after i uncheck that value and save, the data is still in database. However after uncheck it's not shown in field area as checked but still in 'postmeta' table. This prevents value is not empty queries like :

meta_query => array(  
    array(
          'key'=>'sth',
          'value'=>'',
          'compare'=>'!='
    )
)

I do not know that if this is only for me but it would be nice to check it.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
