### ISSUE TITLE
Magic Fields doesn't import every custom fields

### ISSUE THREAD

**Issue by tominardi** [magic-fields-team/Magic-Fields-2#149]
Here is my pnl file :

    a:4:{s:4:"name";s:12:"atl2_membres";s:9:"post_type";a:5:{s:4:"core";a:5:{s:2:"id";s:1:"1";s:4:"type";s:12:"atl2_membres";s:5:"label";s:6:"Membre";s:6:"labels";s:7:"Membres";s:11:"description";s:25:"Les membres du réseau";}s:7:"support";a:7:{s:5:"title";s:1:"1";s:6:"editor";s:1:"1";s:6:"author";s:1:"1";s:9:"thumbnail";s:1:"1";s:7:"excerpt";s:1:"1";s:13:"custom-fields";s:1:"1";s:9:"revisions";s:1:"1";}s:8:"taxonomy";a:2:{s:20:"atl2_membres_secteur";s:1:"1";s:7:"secteur";i:1;}s:6:"option";a:15:{s:6:"public";s:1:"1";s:18:"publicly_queryable";s:1:"1";s:19:"exclude_from_search";s:1:"0";s:7:"show_ui";s:1:"1";s:12:"show_in_menu";s:1:"1";s:13:"menu_position";s:0:"";s:15:"capability_type";s:4:"post";s:12:"hierarchical";s:1:"0";s:11:"has_archive";s:1:"0";s:16:"has_archive_slug";s:0:"";s:7:"rewrite";s:1:"1";s:12:"rewrite_slug";s:6:"membre";s:9:"query_var";s:1:"1";s:10:"can_export";s:1:"1";s:17:"show_in_nav_menus";s:1:"1";}s:5:"label";a:13:{s:4:"name";s:6:"Membre";s:13:"singular_name";s:6:"Membre";s:7:"add_new";s:14:"Ajouter Membre";s:9:"all_items";s:16:"Tous les Membres";s:12:"add_new_item";s:22:"Ajouter nouveau Membre";s:9:"edit_item";s:13:"Editer Membre";s:8:"new_item";s:14:"Nouveau Membre";s:9:"view_item";s:11:"Voir Membre";s:12:"search_items";s:20:"Aucun membre trouvé";s:9:"not_found";s:20:"Aucun membre trouvé";s:18:"not_found_in_trash";s:30:"Aucun membre dans la corbeille";s:17:"parent_item_colon";s:14:"Parent Membre:";s:9:"menu_name";s:6:"Membre";}}s:6:"groups";a:3:{i:0;a:7:{s:2:"id";s:1:"1";s:4:"name";s:25:"atl2_membres_informations";s:5:"label";s:12:"Informations";s:9:"post_type";s:12:"atl2_membres";s:10:"duplicated";s:1:"0";s:8:"expanded";s:1:"1";s:6:"fields";a:2:{i:0;a:12:{s:2:"id";s:1:"1";s:4:"name";s:34:"atl2_membres_informations_effectif";s:5:"label";s:8:"Effectif";s:11:"description";s:17:"Nombre d'employé";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"1";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"0";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:50:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:2:"25";}";}i:1;a:12:{s:2:"id";s:2:"11";s:4:"name";s:35:"atl2_membres_informations_typologie";s:5:"label";s:9:"Typologie";s:11:"description";s:0:"";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"1";s:4:"type";s:8:"dropdown";s:14:"required_field";s:1:"1";s:13:"display_order";s:1:"0";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:136:"a:3:{s:7:"options";s:57:"Entreprise
    Porteur de Projet
    Collectivité
    Association";s:8:"multiple";s:1:"0";s:13:"default_value";s:0:"";}";}}}i:1;a:7:{s:2:"id";s:1:"2";s:4:"name";s:20:"atl2_membres_contact";s:5:"label";s:7:"Contact";s:9:"post_type";s:12:"atl2_membres";s:10:"duplicated";s:1:"0";s:8:"expanded";s:1:"1";s:6:"fields";a:7:{i:0;a:12:{s:2:"id";s:1:"2";s:4:"name";s:28:"atl2_membres_contact_adresse";s:5:"label";s:7:"Adresse";s:11:"description";s:15:"Numéro et voie";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"1";s:13:"display_order";s:1:"0";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:51:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:3:"256";}";}i:1;a:12:{s:2:"id";s:1:"3";s:4:"name";s:32:"atl2_membres_contact_code_postal";s:5:"label";s:11:"Code Postal";s:11:"description";s:0:"";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"1";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:50:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:2:"10";}";}i:2;a:12:{s:2:"id";s:1:"4";s:4:"name";s:26:"atl2_membres_contact_ville";s:5:"label";s:5:"Ville";s:11:"description";s:0:"";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"2";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:51:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:3:"100";}";}i:3;a:12:{s:2:"id";s:1:"7";s:4:"name";s:30:"atl2_membres_contact_telephone";s:5:"label";s:11:"Téléphone";s:11:"description";s:22:"Numéro de téléphone";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"3";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:50:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:2:"25";}";}i:4;a:12:{s:2:"id";s:1:"8";s:4:"name";s:33:"atl2_membres_contact_adresse_mail";s:5:"label";s:12:"Adresse mail";s:11:"description";s:0:"";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"4";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:51:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:3:"256";}";}i:5;a:12:{s:2:"id";s:1:"6";s:4:"name";s:34:"atl2_membres_contact_site_internet";s:5:"label";s:13:"Site Internet";s:11:"description";s:35:"URL du site internet (avec http://)";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"5";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:51:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:3:"256";}";}i:6;a:12:{s:2:"id";s:1:"5";s:4:"name";s:35:"atl2_membres_contact_nom_du_contact";s:5:"label";s:14:"Nom du contact";s:11:"description";s:0:"";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"2";s:4:"type";s:7:"textbox";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"6";s:10:"duplicated";s:1:"1";s:6:"active";s:1:"1";s:7:"options";s:51:"a:2:{s:9:"evalueate";s:1:"1";s:4:"size";s:3:"256";}";}}}i:2;a:7:{s:2:"id";s:1:"3";s:4:"name";s:29:"atl2_membres_gestion_adhesion";s:5:"label";s:22:"Gestion de l'Adhésion";s:9:"post_type";s:12:"atl2_membres";s:10:"duplicated";s:1:"0";s:8:"expanded";s:1:"1";s:6:"fields";a:2:{i:0;a:12:{s:2:"id";s:1:"9";s:4:"name";s:36:"atl2_membres_gestion_adhesion_statut";s:5:"label";s:6:"Statut";s:11:"description";s:34:"Statut de l'adhésion de ce membre";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"3";s:4:"type";s:8:"dropdown";s:14:"required_field";s:1:"1";s:13:"display_order";s:1:"0";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:144:"a:3:{s:7:"options";s:65:"En attente de validation
    En attente de règlement
    À jour
    Exit";s:8:"multiple";s:1:"0";s:13:"default_value";s:0:"";}";}i:1;a:12:{s:2:"id";s:2:"10";s:4:"name";s:44:"atl2_membres_gestion_adhesion_date_dadhesion";s:5:"label";s:16:"Date d'Adhésion";s:11:"description";s:0:"";s:9:"post_type";s:12:"atl2_membres";s:15:"custom_group_id";s:1:"3";s:4:"type";s:10:"datepicker";s:14:"required_field";s:1:"0";s:13:"display_order";s:1:"0";s:10:"duplicated";s:1:"0";s:6:"active";s:1:"1";s:7:"options";s:31:"a:1:{s:6:"format";s:5:"m/d/Y";}";}}}}s:8:"taxonomy";a:0:{}}

Some fields are not included when I import this file.
«Effectif» is the first lost field.
The groupe «Gestion de l'Adhésion» isn't imported.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
