### ISSUE TITLE
MagicFields 2 cache PhpThumb generate image not working

### ISSUE THREAD

**Issue by miguelalva** [magic-fields-team/Magic-Fields-2#150]
I use Magic Fields 2 to upload the images, and show up well, but at different times in different post appear mismatched images changed with this post. When I clear the cache of all pictures magicfields stop working and are broken into a while back to work, until it happens again and stop or match the images with the post.

I have studied the problem more closely:
When we got several different images with the same name in different post, Magicfields 2 generates the name of these pictures with the attributes in the cache folder magicfields in filenames are th_md5 (attributes) _name File

The problem comes if you have multiple files with the same attributes have the same number of md5 and if you have the same you would have the same file name, so at various times I see a different picture in the post do not match, because the images are overwritten .

I tried to generate images with microtime () and working properly, I propose to modify magicfields 2, to fix this bug.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
