### ISSUE TITLE
 jQuery('.mf-field  limit caracters

### ISSUE THREAD

**Issue by amany** [magic-fields-team/Magic-Fields-2#155]
i need to put that function  for limit caracters to a customfield.(length)
do you think it work?
I try to install it in my theme without result for this moment.

jQuery().ready(function() {
        jQuery('.mf-field  :input').each(function(index) {
      id = jQuery(this).attr('id');
      if (id.match(/^magicfields_{news}_\d_\d/)){
        jQuery('#'+id).attr('maxlength','4');
        // more code of you field
      }
  });

});

thank for infos

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
