### ISSUE TITLE
qtranslate + mf2 no post title translation in custom post type

### ISSUE THREAD

**Issue by drivebass** [magic-fields-team/Magic-Fields-2#157]
I'm creating custom post types with **Magic Fields v2.0.1** 
and i use the **qTranslate v2.5.32** plugin for a second language 
on **Wordpress 3.4.2**. 

The problem is when i select to support only "Title" in the settings of the custom post type and not "Editor" there is no extra Post tile field in the Custom Post Type. If the the "Editor" is on in the settings the post title has 2 fields one for each language normally but i don't want the default visual html editor to appear. I want just the English and second language Title fields. 

Has anyone run on this? Any work out?! Please help!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
