### ISSUE TITLE
Admin bar appearing in image uploader iframe (Re #166)

### ISSUE THREAD

**Issue by samoakley** [magic-fields-team/Magic-Fields-2#167]
I'm referring to an unresolved issue from a previous submission, which was closed recently before I wa able to follow up.

$inputName for the customfield "coverimage" seems to be fed in in this format, rather than being converted to URL-friendly format:

http://www.sitename.co.uk/wp-content/plugins/magic-fields/RCCWP_upload.php?input_name=magicfields%5Bcoverimage%5D%5B1%5D%5B1%5D&type=1&imageThumbID=img_thumb_magicfields_coverimage_1_1&canvas=0

The upshot of this is that a 404 error page is inserted into the iframe, making image uploads in the post admin area impossible.

ie, I'm assuming that:

magicfields[coverimage][1][1]

which is urlencoded to:
magicfields%5Bcoverimage%5D%5B1%5D%5B1%5D

should be converted to:
magicfields_coverimage_1_1

Now, I'm using 1.4.5 (wp 3.4.1) , and suspect this has to do with a conversion to php5.3.

Can you help, please?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
