### ISSUE TITLE
Problem with filtering (magic fields 1.5.8.1, Wordpress 3.4.2)

### ISSUE THREAD

**Issue by KpDevTeam** [magic-fields-team/Magic-Fields-2#171]
Hello, 

First of all, great plugin for Wordpress, but we found a bug when filtering custom posts.
On the first click on "Filter" button, it works just fine, but if we click one more time, and don't change anything else, the page goes to the default posts.
It seems that on second click, the filter-posts and custom-write-panel-id parameters in the url for edit.php page, are lost.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
