### ISSUE TITLE
Multiple images in group not displaying 

### ISSUE THREAD

**Issue by drivebass** [magic-fields-team/Magic-Fields-2#173]
Magic Fields v2:
I'm using the get_group function to display duplicate image fields like this:
```
<?php $photos = get_group('photos'); ?> 
<?php foreach($photos as $photo){?>
<div class="project_photo">
<img src="<?php echo $photo['project_photo'][1]['o']; ?>">
</div>
```

It just returns 
```
<img src>
```

 It is working perfect with magic fields version 1 but on 2 it appears to do nothing. Any ideas?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
