### ISSUE TITLE
Plugin causes RSS Validation Error

### ISSUE THREAD

**Issue by Keith1000** [magic-fields-team/Magic-Fields-2#178]
Magic Fields Plugin or combination of this plugin and another plugin results in an error in the RSS feed :-

Cannot modify header information - headers already sent by

Wordpress version   3.5.1
Magic Fields Plugin Version  2.1 ( http://magicfields.org/ )
Other relevant Plugin  Wordpress SEO By Joost De Valk  Version  1.3.4.4 (http://yoast.com/wordpress/seo/ )

Background Information
The problem occur of the website  www.maitebaron.com  the RSS feed having this error.  The error can be checked by using the W3C Feed Validation Service
http://validator.w3.org/

enter the URL   www.maitebaron.com/feed

A copy of this website has been made and installed in the following URL

http://beyondcorporatenow.com/

The theme has been set back to the default  2010 Wordpress theme. 

All Plugins apart for the Magic Fields and The Wordpress SEO have been removed. 

All magic fields have been removed.  So the installation in www.beyondcorporatenow.com has been reduced to the bare bones.

If either plugin is deactivated the RSS validation error goes away.

Use the w3C validator with www.beyondcorporatenow.com is the error condition.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
