### ISSUE TITLE
Use custom permalink settings

### ISSUE THREAD

**Issue by polarblau** [magic-fields-team/Magic-Fields-2#179]
We’re using custom permalinks containing dynamic elements (in our case the year) and we’d like the URLs for posts of a custom type to behave the same way. Is this behaviour currently supported (—I hope I'm not missing something obvious)?

Naturally I can define a rewrite rule for my post type, 

![Screen Shot 2013-03-07 at 15 52 38](https://f.cloud.github.com/assets/123923/232308/641d0e2c-872e-11e2-963d-c115e5237f2b.png)

but these rules don’t seem to allow dynamic elements such as WP's permalink settings do:

![Screen Shot 2013-03-07 at 15 53 12](https://f.cloud.github.com/assets/123923/232307/6419f728-872e-11e2-8f5f-ed8ea172863a.png)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
