### ISSUE TITLE
QTranlate, the duplicated multiline fields delete the post content in the main area

### ISSUE THREAD

**Issue by apuestokid** [magic-fields-team/Magic-Fields-2#183]
Hello
I'm using qTranslate (2.5.34) WP (3.5.1) and Magic Fieds 2 (2.1) 
And i'm having a problem with multiline duplicated fields.
I've created a custom post type with a meta box that "CAN BE DUPLICATED". The box contains a textarea, and a multiline, when I duplicate the metabox it duplicates both fields.

If I don't duplicate the metabox, it works fine, but in the admin area, when i duplicate the metabox, when i save the post, the last multiline content, is copied to the main language post content, and the post content is deleted.
Ass you see in the picture "content metabox 02" is copied to the main post content.
![Captura de pantalla 2013-03-15 a la s 12 16 08](https://f.cloud.github.com/assets/3874029/263244/05c73010-8d63-11e2-90e2-c136fbc62b43.png)
¿Anyone have this problem? ¿Any solution?

Thanks

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
