### ISSUE TITLE
[Bug?] Why if i click on 'Quantity' option, it appears 'add post'? [See pic]

### ISSUE THREAD

**Issue by misterfulanito** [magic-fields-team/Magic-Fields-2#185]
Hi, i'm guessing why if i set up my CPT like a 'page' and check the 'Quantity' option it hides 'Show All Posts' and let 'Add More Posts' when in theory it's viceversa?.

See the pic, thank you.

(Below: I have a CPT called 'Instrumento(s)', set it up like 'page' and the 'Quantity' is checked but the 'add more Instrumentos' is showing up).

![Captura de pantalla 2013-03-22 a la s 17 42 57 2 ](https://f.cloud.github.com/assets/813025/293194/837f79bc-934a-11e2-8a44-68b381b73255.png)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
