### ISSUE TITLE
Multiline field loading older version of TinyMCE tools

### ISSUE THREAD

**Issue by jordesign** [magic-fields-team/Magic-Fields-2#186]
Strange issue that I've found occuring with Multiline fields. It only happens when the edit screen loads with the main content field in 'Text' instead of 'Visual'. 

In this instance the other multiline fields load with an older looking version of the tool 'buttons'. It also changes the source of img references in the field - adding a preceding '../'

![Screen Shot 2013-04-12 at 5 00 05 PM](https://f.cloud.github.com/assets/1842363/371612/d304d37a-a33e-11e2-8e2f-03b6fd3c6cb0.png)

If the main editor is set to 'Visual' when saved (and reloaded) then both the main editor, and other multiline fileds load the nice set of TinyMCE buttons.

![Screen Shot 2013-04-12 at 5 00 26 PM](https://f.cloud.github.com/assets/1842363/371614/dae00312-a33e-11e2-81f4-64cb0c8cd954.png)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
