### ISSUE TITLE
Toolbar "Add New" overwrites setting Post Type as one element

### ISSUE THREAD

**Issue by carlitocenteno** [magic-fields-team/Magic-Fields-2#187]
My client managed to add an additional entry through the WordPress toolbar at the top on a post type that is marked to display as one element. Consequently, the website displays both entries. I can change the front-end code to display only the latest entry but this defeats the purpose of the feature.

I hope this is enough information to solve the problem.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
