### ISSUE TITLE
[Bug] Don`t save custom fields value

### ISSUE THREAD

**Issue by asergiychuk** [magic-fields-team/Magic-Fields-2#188]
WordPress 3.5.1
Magic Fields 2.1

I made custom fields. Saved post, but my custom fields were empty. When I was looking for what happend I found MF_TABLE_POST_META field called "meta_id" but It was called in the table just "id". When I renamed field name in the table, it was started work.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
