### ISSUE TITLE
Custom Fields not displaying after saving in the post 

### ISSUE THREAD

**Issue by PHironaka** [magic-fields-team/Magic-Fields-2#190]
I recently had to switch web hosting and in the process to set up a new DB. As a result, I lost all the custom post types I had previously creating with Magic Fields 2. I've re-installed Magic Fields onto this new Database I'm working on and have run into an issue saving posts.

I've created a new post-type with an identical name and fields/groups. When I try to create a new post within the custom post-type, the images and text I enter in disappears upon saving.

What could the issue be? Is this something that can be restored within previous back-up files?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
