### ISSUE TITLE
No control for search results 

### ISSUE THREAD

**Issue by sithadro** [magic-fields-team/Magic-Fields-2#193]
Hi,

If my page is created in Magic Fields 2 plugin (page format, include search) and has assigned custom template, the search result not used search.php.

Example: http://www.ogrodypoolex.pl/

When your search the "Mazenna" phrase, wordpress diplay results using search.php ("Mazenna" phrase exists only in "Kontakt" page (standard page format)

When you search the "ogrody" phrase, wordpress diplay results using custom page template   oferta-page.php. ("ogrody" phrase exists on many custom pages which using oferta-page.php template).

Is it possible to wordpress use only search.php  template?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
