### ISSUE TITLE
Problem with ajax requests

### ISSUE THREAD

**Issue by daryush** [magic-fields-team/Magic-Fields-2#195]
When I move my project to production server, I've got a problem with every ajax request in Magic Fields 2. I. e. When I try to Edit Custom Field, after pressing Save Custom Field submit button nothing happens. I go to the code and find action in the mf_admin.js and add little code to catch error in ajax request:

  //validation custom field
  $('#addCustomField').submit(function(){
    name = $("#customfield-name").val();
    field_id = $("#customfield_id").val();
    post_type = $("#customfield-post_type").val();
    var status = 0;
    if(name){
      jQuery.ajax({
         url: ajaxurl,
         type: 'POST',
         async: false,
         dataType: 'json',
         data: "action=mf_call&type=check_name_custom_field&field_name="+name+"&post_type="+post_type+"&field_id="+field_id,
         success: function(response){
           $("#message_mf_error").hide();
           if(response.success){
             status = 1;
           }else{
             $('#message_mf_error p').empty().append(response.msg);
             $("#message_mf_error").show();
             $("#customfield-name").focus();
           }
         },
         error: function(jqXHR, textStatus, errorThrown){
            console.log(textStatus);
         }
       });
    }
    if(status)
      return true;
      
    return false;    
  });

After that, when I push this button on console I've got 'parseerror'. What can be wrong on this specific server that causing this error? Or what is wrong with plugin.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
