### ISSUE TITLE
File Upload Field is missing

### ISSUE THREAD

**Issue by ivzgrace** [magic-fields-team/Magic-Fields-2#196]
Hi,

We used magic fields for our client's monthly bulletin board, however last June the encounter this problem that the file upload field is not working anymore. We already tried fixing it and unfortunately we don't have luck. 

Can anyone help me please? This is the screenshot on how it looks http://screencast.com/t/DQmVXZcOTcZ

Website is: http://www.hrlc.org.au/monthly-bulletin

Thanks,

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
