### ISSUE TITLE
plugin conflict with LayerSlider

### ISSUE THREAD

**Issue by ghost** [magic-fields-team/Magic-Fields-2#197]
hi there,
i've got this message from LayerSlider developers:

This plugin is currently doesn't handle their own resource files properly and loads them on admin pages where it shouldn't with causing conflict with other scripts and plugins. One of their Javascript files overriding the AJAX functions of jQuery that breaks the saving mechanism in LayerSlider. The best would be if you could contact with the plugin author, so they can fix it and you don't have to bother with it again if you update the plugin or change anything.

it'd be great if someone could fix that.
thanks,
Adam

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
