### ISSUE TITLE
WYSIWYG editor not instantiated on multiline fields without content field

### ISSUE THREAD

**Issue by polarblau** [magic-fields-team/Magic-Fields-2#198]
When creating multiline input fields with WYSIWYG editor within a group, the WYSIWYG editor doesn’t get instantiated if the post type doesn’t have a content field.

**How to reproduce:**

1. Create a new post type, don't check anything under `Support`
2. Edit fields and groups > Add group
3. Add field of type `multiline` to the group
4. Create instance of the new post type

The WYSIWYG should not be showing, what you get looks something like this:

![screen shot 2013-07-11 at 00 06 45](https://f.cloud.github.com/assets/123923/777929/abc213c0-e9a4-11e2-840a-d076362189ee.png)

In addition two Javascript errors register which seem related:

```
Uncaught TypeError: Cannot read property 'language' of undefined wp-tinymce.php:36
Failed to load resource: the server responded with a status of 404 (Not Found) http://[…SNIP…]/wp-includes/js/tinymce/themes/advanced/skins/wp_theme/ui.css?ver=358-24486
```

I'm assuming that some dependencies required for the editor aren’t met if the post doesn’t have a content field — maybe WP doesn’t load TinyMCE JS files in this case? 

This issue has been registered on WP 3.5.2.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
