### ISSUE TITLE
Setting a rewrite for post type breaks parent/child urls if same rewrite is used

### ISSUE THREAD

**Issue by rockymountainhigh1943** [magic-fields-team/Magic-Fields-2#199]
If I set the rewrite to /about, then my page URL does exactly what I want (domain.com/about/new-page). But if a page titled About already exists and it has a child page (domain.com/about/child-page) - the page returns a 404 error.

Please fix this. I rely on this plugin a lot and would hate to switch over to something else.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
