### ISSUE TITLE
Cannot set rewrite to "/" so as to prevent prepending post type - breaks permalinks

### ISSUE THREAD

**Issue by rockymountainhigh1943** [magic-fields-team/Magic-Fields-2#200]
Whenever you set a rewrite to "/" it breaks all the other permalinks on the site. All I want to do in this instance is not have the post type prepended to the permalink (so domain.com/page-name not domain.com/post-type/page-name).

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
