### ISSUE TITLE
Non-network admins can't access settings pages in MU

### ISSUE THREAD

**Issue by tom-thetazulu** [magic-fields-team/Magic-Fields-2#201]
Hi,

We run an MU install with 300+ sites attached. We've got your plugin installed but have noticed that a site administrator is always told that they have insufficient privileges to view the Magic Fields menu at the bottom of the left hand navigation. The only sub-menu available is "Import".

Network admins can see the full functionality, and the menu under Settings -> Magic Fields is unaffected, this is only the menu at the bottom of the left nav.

![image](https://f.cloud.github.com/assets/936775/926671/f3402e34-ff8f-11e2-8343-dba5b70e3ddf.png)

![image](https://f.cloud.github.com/assets/936775/926684/4c0c455c-ff90-11e2-9bf0-bf34fc9d0c32.png)

See screens above.

The user is an administrator on this site, but not a superadmin.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
