### ISSUE TITLE
robots.txt is being handled incorrectly

### ISSUE THREAD

**Issue by clarkewd** [magic-fields-team/Magic-Fields-2#205]
appears to be a problem with your code here:

https://github.com/magic-fields-team/Magic-Fields-2/blob/master/main.php#L315

when the plugin is enabled the robots.txt file is duplicated (just enable this plugin and visit /robots.txt to test

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
