### ISSUE TITLE
Image impossible to insert in Field (magic field upload image) - wordpress v3.6

### ISSUE THREAD

**Issue by advancedcreation** [magic-fields-team/Magic-Fields-2#206]
Hello,

I saw a bug with wordpress v3.6 and image upload by magic field,

So when you create a field (image media upload) by magic field 1 or 2 (I tested both)
and you upload an image to link to your specific field, the button "Set image in field" in not display, so this is not possible anymore to add an image in a field inside magic field,

Please let me know if you find the problem
Thanks

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks

**Comment by PokatilovArt** [comment]
Faced the same problem. WP 4.8.1, Magic Fields 2.1
No "Insert to field" button.
Added multiline box - no changes.
