### ISSUE TITLE
Add to Overview Page (edit.php)

### ISSUE THREAD

**Issue by mmalta** [magic-fields-team/Magic-Fields-2#21]
Here is an excellent snippet from Yoast:
http://yoast.com/custom-post-type-snippets/

I used this in my functions.php to show information from the post in the admin area. 
You can see a sample here http://cl.ly/3S0U432p0o3h2j2j0M0l

This seems like something rather simple you could implement or give an option for? Thanks!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
