### ISSUE TITLE
Magic Fields causing an error when uploading images

### ISSUE THREAD

**Issue by JaneDarb** [magic-fields-team/Magic-Fields-2#213]
I have a wordpress site with woocommerce integrated. When the Magic fields plugin is activated, I cannot uplaod new images or see images in my media library when in the woocommerce product area. When I deactivate the Magicfields pluggin, I can upload images, but of course get an error on my home page where the magicfields pluggin is being used. 

Has anyone had this problem, or can anyone help me with a fix?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
