### ISSUE TITLE
Custom Post Type Template not found in child theme

### ISSUE THREAD

**Issue by one-cog-mind** [magic-fields-team/Magic-Fields-2#214]
When a custom post type is created with "page attributes" enabled and the the post template is set to a custom template the plugin does not find the template located in the child theme.

For example;
main theme location: /wp-content/themes/responsive
child theme location: /wp-content/themes/responsive-child

Custom post template file: /wp-content/themes/responsive-child/ride-event.php

The following error is shown (using local VM).

Warning: include(/vagrant/wordpress/wp-content/themes/responsive/ride-event.php): failed to open stream: No such file or directory in /vagrant/wordpress/wp-content/plugins/magic-fields-2/main.php on line 337 Warning: include(): Failed opening '/vagrant/wordpress/wp-content/themes/responsive/ride-event.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/wordpress/wp-content/plugins/magic-fields-2/main.php on line 337

When I copy the file 
/wp-content/themes/responsive-child/ride-event.php
-to-
/wp-content/themes/responsive/ride-event.php

it works fine.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
