### ISSUE TITLE
Unable to save fields

### ISSUE THREAD

**Issue by mateeb4u** [magic-fields-team/Magic-Fields-2#215]
hi, 
i am using magic-fields, it helps me alot, in many wesite, and it working well, but currently issue that when , iam working on another site in that i make fields and when try to save their values by (publish/update) it dont save the value, is there is issue in website or plugin is not integrating proprly, 
thanks
word press 3.7.1

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
