### ISSUE TITLE
Field Multiline not load. WP 3.8

### ISSUE THREAD

**Issue by oscarmolinadev** [magic-fields-team/Magic-Fields-2#218]
Field Multiline not load in Wordpress 3.8.

Error: wp-includes/js/tinymce/langs/en.js not found.

Wordpress 3.8 renamed en.js to wp-langs-en.js

Temporary Solution: Change name wp-langs-en.js to en.js and works correctly

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
