### ISSUE TITLE
New Post / Page (magic field 1.x)

### ISSUE THREAD

**Issue by advancedcreation** [magic-fields-team/Magic-Fields-2#220]
Hello,

I noticed a little bug a little anoying,

When we are inside a multi page or multipost in white panel and want to create a new one, 
we are creating a regular post/page wordpress, so basically to bring it back inside the white panel, we have to:
Publish it
choose the white panel and publish it again

Can you fix that to be sure we stay inside the good white panel ?

Thank you
Oli

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
