### ISSUE TITLE
Error URL on post type pagination (back end admin)

### ISSUE THREAD

**Issue by gplaza** [magic-fields-team/Magic-Fields-2#222]
Hi,

I have a problem about the URL in my magic field's post type :

Url for the second page of a post type (admin : edit) :
http://xxx.cl/wp-admin/edit.php?post_type=aciones?post_type=aciones&paged=2

like you can see there is a doble "?" ....
Where is generated this link for a new custon type ?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
