### ISSUE TITLE
enable l10n for admin menu items

### ISSUE THREAD

**Issue by lislis** [magic-fields-team/Magic-Fields-2#225]
Is there a possibility to wrap the labels for created custom post types in __()?
I need to make the labels in the admin menu translatable.

EDIT:
I did a workaround for this now.
In the mf_register.php I commented out line 38 where the labels get assigned. And I assign them myself 

```
      $new_labels = array();
      foreach ($p['label'] as $k => $v) {
        $new_labels[$k] = __($v, 'theme_textdomain');
      }
      $options['labels'] = $new_labels;
```
Then I can add all the terms I need to my theme's .po and .mo files. The problem is that is is not really dynamic, because I need to hardcode my theme's textdomain.
Some thoughts on that would be appreciated :)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
