### ISSUE TITLE
MF 2.2.2.1 fails to get post id

### ISSUE THREAD

**Issue by jswright61** [magic-fields-team/Magic-Fields-2#227]
Using MF 2.2.2.1 with Wordpress 3.9.1, I get the following error:
Notice: Trying to get property of non-object in /var/www/wp-content/plugins/magic-fields-2/mf_front_end.php on line 15.

Possibly related, Wordpress will not display the correct single template for this custom post type.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
