### ISSUE TITLE
Image Media Fails

### ISSUE THREAD

**Issue by juliocarchila** [magic-fields-team/Magic-Fields-2#228]
Hi, I was working on a site where I need a post_type that should contain an image field, but in the moment I create that "image media" field and I try to make a new post in that specific post_type, everything seems to be wrong, I mean, the unicode changes, and if I have a post and I add a new one, this last post overwrite the post I had.

It worked well when I changed the "image media" field for an "image" field. So, maybe, you can work on it to fix this issue in the next version.

Best regards!

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
