### ISSUE TITLE
Magic Fields and AAM(Advanced Acces Manager) conflicts.

### ISSUE THREAD

**Issue by oscarmolinadev** [magic-fields-team/Magic-Fields-2#229]
i have installed:

Magic Fields 2.2.2.1
Advanced Access Manager 2.7

AAM not working, infinite loading. The problem is jquery.validate of Magic Fields 2. MF 2 have old version of jquery.validate 1.7 released in 2009-06-17 14:27:16. if upgraded to last version of jquery.validate both plugins works correctly.

Thanks.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
