### ISSUE TITLE
Media > Attach Error - No Pages load

### ISSUE THREAD

**Issue by spyderweb56** [magic-fields-team/Magic-Fields-2#235]
When trying to attach an image from the Media section to a post, I click the "Attach" link under the "Uploaded To" column and the popup to Find a Post or Page spins for a second then says "An error has occurred. Please reload the page and try again."

I've deactivated all plugins and narrowed it down to Magic Fields 2.2.2.2. This issue is on a LIVE site so I need to get this addressed asap. Any guidance would be greatly appreciated.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
