### ISSUE TITLE
WP-Editor HTML code before <!DOCTYPE html>

### ISSUE THREAD

**Issue by alvaroleon** [magic-fields-team/Magic-Fields-2#237]
When I remove the native editor Wordpress in post type and add a multiline type, lines are added before <!DOCTYPE html> tag. This bug does not allow editing text in some browsers...

![sin titulo](https://cloud.githubusercontent.com/assets/2080180/4235854/17ddda66-39c3-11e4-9c66-7b56878d7a66.png)

I fixed it adding a filter "admin_footer" in admin/mf_post.php file: 
Line: 503: 
```php
if( (in_array('multiline',$fields) || in_array('image_media',$fields) )  && !post_type_supports($post_type,'editor' ) ){
	echo "<div style = 'display: none'>"; 
	wp_editor('', 'you_know_nothing'); 
	echo "</ div>"; 
}
```

Replace with: 

```php
if( (in_array('multiline',$fields) || in_array('image_media',$fields) )  && !post_type_supports($post_type,'editor' ) ){
	function add_editor() {
		echo "<div style = 'display: none'>"; 
		wp_editor('', 'you_know_nothing'); 
		echo "</ div>"; 
	} 

	add_filter ('admin_footer', 'add_editor');
}
```

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
