### ISSUE TITLE
Magic Fields disables WP Admin features

### ISSUE THREAD

**Issue by benos229** [magic-fields-team/Magic-Fields-2#238]
Hi. When I have magic fields 2 activated I can no longer use certain features within the WP admin. For example when I click on the "Upload/Insert" option on the 'edit post' or 'edit page' screens nothing happens. Similarly the options in the top right of the WP admin screen are also unresponsive e.g. log out dropdown, screen options dropdown, help dropdown etc.

When I deactivate magic fields 2 everything works fine?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
