### ISSUE TITLE
taxonomy & post type dropdown fields

### ISSUE THREAD

**Issue by studioleland** [magic-fields-team/Magic-Fields-2#24]
Any chance you guys could allow for a dropdown or dropdown multiselect to display custom post type and/or custom taxonomy selections?  That would be very useful for building pages where the editor can select a category or post type for the loop on that page.  Ideas? or is there a better way to do this?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
