### ISSUE TITLE
Email address issues

### ISSUE THREAD

**Issue by OceanWind** [magic-fields-team/Magic-Fields-2#242]
I'm running into an issue with email addresses being inserted into a field and automatically detected/turned into links where the email domain has more than one '.' (dot). For example, if I insert the email address "joesmith@someplace.com.mx", it converts this into a link, but does not include the critical ".mx" at the end. The parsing routine seems to detect only 1 dot in the domain name.

I tried turning TinyMCE on for the field and creating the link manually using the link button. But other issues arise there where the opening of the <a> tag is not recognized correctly. The parse/auto-link routine seems to be overriding it.

Any ideas?

Bill

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
