### ISSUE TITLE
create_image broken since 2.3.2.2

### ISSUE THREAD

**Issue by opi99** [magic-fields-team/Magic-Fields-2#244]
Since commit https://github.com/magic-fields-team/Magic-Fields-2/commit/1d57f206f6b3d4890313419314bafe4b404843f7 (Better error handling) the create_image function is broken. See my comment in the commit themself.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks

**Comment by opi99** [comment]
Is ok, was fixed with commit 83af7deccdf0bd55f64dbcf7889813ef739fe887 a half year ago (2 days after my comment).
