### ISSUE TITLE
TEMPLATEPATH is deprecated, use get_stylesheet_directory() for supporting child themes

### ISSUE THREAD

**Issue by acorbi** [magic-fields-team/Magic-Fields-2#246]
WP 4.5.2
Magic fields 2.3.2.4

On https://github.com/magic-fields-team/Magic-Fields-2/blob/master/main.php#L392 the plugin checks if _wp_mf_page_template is set on the post meta and if so, loads the configured one. In a parent-child theme scenario, TEMPLATEPATH points to the parent template when the excepted path should be that of the child.

TEMPLATEPATH has been aparently deprecated in WP 4.5, read more on http://stackoverflow.com/questions/3863461/wordpress-templatepath and https://core.trac.wordpress.org/ticket/18298. 

PR with fix on https://github.com/magic-fields-team/Magic-Fields-2/pull/247

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
