### ISSUE TITLE
Wordpress 4.6 - custom fields lost data

### ISSUE THREAD

**Issue by simkea** [magic-fields-team/Magic-Fields-2#248]
Hello,
we have an error after update from wordpress 4.5.x to 4.6
installed version of MagicFields is 2.3.2.4

when I save an edited post then the data is lost from all custom fields and blank values ​​are stored. 
is this problem solved in new version of MF (2.3.3)?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks

**Comment by davidensinger** [comment]
I am experiencing this same issue and have updated to 2.3.3. @simkea did you figure out a workaround?
