### ISSUE TITLE
display or not :) `?

### ISSUE THREAD

**Issue by simkea** [magic-fields-team/Magic-Fields-2#250]
File: multiline_field.php
Line 106: 		  `printf('<div style="display: none1" id="wp-%s-media-buttons" class="wp-media-buttons mf_media_button_div" >',$field['input_id']);`

-> Display: none1 or none; 

br

**Comment by hunk** [comment]
I don't know and at this point, I'm afraid to ask :p 

ok this came from this [pull request](https://github.com/hunk/Magic-Fields/pull/157/commits/ea96e471daa744beb466a152b863b010568ea344) from 2012, but 2014 we have problems and send [this fix](https://github.com/magic-fields-team/Magic-Fields-2/commit/6b054a7e578b86baacbddedb00d70ac7dfb892c5) I suppose at begin of debugging I change display: none  for show what happened with this buttons and I forget to remove the display: none1

but in this commit i remove that.

thanks for the report
