### ISSUE TITLE
Date Picker not working with Wordpress 5.5 Update

### ISSUE THREAD

**Issue by reaxion** [magic-fields-team/Magic-Fields-2#271]
As of the Wordpress 5.5 update, the date picker field (pop out calendar picker) will not work with MagicFields 2.3.3.1 or 2.3.2.4, but will work with the the version preceding 5.5.

Thank you!

**Comment by tr3intaydos** [comment]
WordPress 5.5 was released without jQuery Migrate used for old jQuery Code,
you need to install:


https://wordpress.org/plugins/enable-jquery-migrate-helper/


Or a PR.

**Comment by reaxion** [comment]
Wow! Works like a charm! Thank you so much!
