### ISSUE TITLE
Broken after Wordpress 5.4.4

### ISSUE THREAD

**Issue by enuggetry** [magic-fields-team/Magic-Fields-2#272]
It's having problems after Wordpress 5.4.4.

- date fields cannot be edited
- text fields cannot be edited.

**Comment by tr3intaydos** [comment]
you have to install [Enable jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/)

**Comment by enuggetry** [comment]
This resolved the problem.  Thanks.
