### ISSUE TITLE
Feature request: Sortable field duplicates

### ISSUE THREAD

**Issue by EivindFS** [magic-fields-team/Magic-Fields-2#29]
Hey,

We can sort group duplicates in the UI. I love this function. It is very important from a usability point of view. Equally important - ALMOST equally important - is sortable field duplicates.

I would very much like to see this in the future. As it is now, I must create workarounds using groups for just one field or I must put more work on my client (cut/delete the content of one field, move it to another etc).

Cheers,
Eivind

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
