### ISSUE TITLE
Possible bug: 404 on post type URL rewrites

### ISSUE THREAD

**Issue by EivindFS** [magic-fields-team/Magic-Fields-2#33]
Hey guys,

When I enable URL rewrite on my posts the permalinks throw 404s. When I disable it, they start working again.

I'm not sure if I'm doing something wrong or if there is a bug. I figured I'd report it anyway.

Cheers,
Eivind

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
