### ISSUE TITLE
Unable to use fields unless Custom Post Type is publicly accessible

### ISSUE THREAD

**Issue by cmwelsh** [magic-fields-team/Magic-Fields-2#47]
I have a custom post type that I'm using to create a quick custom list.

    public function init() {
        register_post_type($this->postType,
            array(
                'labels' => array(
                    'name' => __('Historic Championships'),
                    'singular_name' => __( 'Historic Championships' )
                ),
                'public' => false,
                'show_ui' => true,
                'has_archive' => false,
                'supports' => array('title', 'page-attributes'),
            )
        );
    }

I can't seem to add and edit Magic Fields on this post type unless I change public to true. Is this a bug, or intentional? I would appreciate some clarification on this behavior. Thanks. :)

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
