### ISSUE TITLE
Feature request - Conditional form field (If yes radiobox clicked show another form field)

### ISSUE THREAD

**Issue by mistergiri** [magic-fields-team/Magic-Fields-2#49]
Just check this demo.

http://www.onextrapixel.com/examples/jquery-cookie/

You can see this question there.

"Are you above 21 yrs old?"

If you click "No" radio button you can see another two forms fields appears below that question.

Could you please add this feature in our magic fields plugin?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
