### ISSUE TITLE
Some kind of thumbnail for file field

### ISSUE THREAD

**Issue by kieranbarnes** [magic-fields-team/Magic-Fields-2#52]
When using the the file field its not obvious if the field already has a value when editing the page.
There is a box for a thumbnail (like the 'image' field) but is empty regardless of whether the field has a value set.

Perhaps display the file path or a WP Media style icon in the box to show if the field has a value.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
