### ISSUE TITLE
Getting errors while import 

### ISSUE THREAD

**Issue by mistergiri** [magic-fields-team/Magic-Fields-2#57]
I'm using very latest magic fields 2.0 version. Wordpress version: 3.2.1
I'm getting the following errors while importing magic fields template which i created in localhost

Warning: Invalid argument supplied for foreach() in /public_html/wp-content/plugins/mf/admin/mf_admin.php on line 385

Warning: Invalid argument supplied for foreach() in /public_html/wp-content/plugins/mf/admin/mf_admin.php on line 451

Warning: unlink() [function.unlink]: No such file or directory in /public_html/wp-content/plugins/mf/admin/mf_posttype.php on line 836

Warning: Cannot modify header information - headers already sent by (output started at /public_html/wp-content/plugins/mf/admin/mf_admin.php:385) in /public_html/wp-includes/pluggable.php on line 934

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
