### ISSUE TITLE
Taxonomies not working with QMT

### ISSUE THREAD

**Issue by sr83** [magic-fields-team/Magic-Fields-2#58]
I have been testing MF 2 beta and it appears it is not compatible with the QMT (Query Multiple Taxonomies) plugin.

I have used QMT successfully with other plugins (Custom Post Tyes UI, etc). I have tried creating custom post types using taxonomies created in MF2 and the taxonomy filtering does not work.

When I assign a MF2 created taxonomy to a MF2 custom post type only the the standard posts show in the results pages using QMT.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
