### ISSUE TITLE
Feature Request - Nested Content Types / Taxonomies Custom fields

### ISSUE THREAD

**Issue by asalce** [magic-fields-team/Magic-Fields-2#61]
I have a taxonomy called "Schools" which I would like to also attach certain data. Like: Yearly Tuition (Textfield), Degrees (Duplicable text field)

A work around could also be Nested Content Types. So I can create a "Schools" content type with my custom meta fields and have the "Add Schools" , "All Schools" link show IN the "Post" sub-menu. Then I can add a custom Related field (Duplicable) to the "Post" content type.

I like the "Nested" content type idea better than adding Custom fields to Taxonomies. I could pontentially do this already via Functions PHP and adding my own "add_submenu_page" to Posts which links to my custom content types, but it would be cool if it were built in somehow.

Any thoughts?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
