### ISSUE TITLE
ÅÄÖ in uploads - sanitize file names

### ISSUE THREAD

**Issue by jteg** [magic-fields-team/Magic-Fields-2#68]
When uploading an image you get an error if the file name contains certain special characters, as for instance the swedish ÅÄÖ. The image uploads to the server but MF fails to create thumbnails and no thumbnail image shows. This was a problem also in MF 1.x and I've solved it earlier following these steps:

http://groups.google.com/group/magic-fields/browse_thread/thread/b8359eeb8f91e8ed/0e3d1a6dd7e5b406?lnk=gst&q=sanitize#0e3d1a6dd7e5b406

Maybe its time to switch the function that sanitizes file names to the one in this link?

Best regards,
Jonas

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
