### ISSUE TITLE
Feature request: Write panel icons

### ISSUE THREAD

**Issue by EivindFS** [magic-fields-team/Magic-Fields-2#7]
Hey guys,

I don't know if this is the right place for a user request. 

What I would like is for every Write Panel to come with the option to specify a custom icon image, giving me the opportunity to replace the pin with say a music or a cd icon. That would help the UI immeasurably.

This would be a great feature I think.

Cheers,
Eivind

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
