### ISSUE TITLE
Custom fields within custom group not saving

### ISSUE THREAD

**Issue by thirdboxcar** [magic-fields-team/Magic-Fields-2#75]
I'm once again trying to use Magic Fields for a restaurant menu (oh how I wish you'd allow nested groups!). I tried out MF2, but am about to revert to MF1 because of this huge issue:

I have a write panel with one duplicatable group with three fields inside it. When I add content to these three fields and save the post, the content disappears. The content shows up under Custom Fields if I enable that field, but I would prefer not to. I want it to show up in my magic fields group & fields!

This doesn't happen with MF1, so I'm pretty sure this is a bug. I'm using the latest version of WP and the latest version of the code hosted here on github.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
