### ISSUE TITLE
Choose another post type as parent?

### ISSUE THREAD

**Issue by alexandergryth** [magic-fields-team/Magic-Fields-2#77]
Awesome work with the new MF-version.
Just got one big problem. I cant seem to figure out how to get one post type to be the parent of another, as you could do in the previous MF-version.
I would like to have these nice looking hieracial URLs like mytravelcompany.com/country/travel-category/travel/ etc. where country is one posttype, travel-category is another with a completely different set of fields and travel is yet another post type and so on.

This is whats keeping me from using the new version. Is there anything I'm missing, because this was the single best thing that Magic Fields 1 contibuted to wordpress.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
