### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by kieranbarnes** [magic-fields-team/Magic-Fields-2#78]
I've been debugging some slow code recently.

When a customer uploads a large image into a MagicFields2 image field I see two requests called on top of the media-uploader.php.

Can someone explain why MF2 calls 

/wp-content/plugins/magic-fields/admin/MF_ImageMedia.php
/wp-content/plugins/magic-fields/thirdparty/phpthumb/phpThumb.php

aswell? It doesn't seem to produce anything useful.

On top of that, when referencing the image, MF2 returns

   [images_image] => Array
        (
            [1] => Array
                (
                    [original] => http://xxxxxxxxxx/wp-content/uploads/2011/10/65718toy.jpg
                    [thumb] => http://xxxxxxxxxx/wp-content/uploads/2011/10/65718toy.jpg
                )

        )

Why does MF2 return original and thumb as the same value.

I guess MF2 isn't using the WP Media Settings to auto create me a thumbnail, but it isn't creating a thumbnail at all.
As you can see both files are the same in the array above. 

Why isn't MF2 creating and returning a thumbnail based on my WP Media Settings?

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
