### ISSUE TITLE
WordPress Network Mode (MU)

### ISSUE THREAD

**Issue by VitaliyKaplya** [magic-fields-team/Magic-Fields-2#82]
There are problems when adding a new site in the network mode, when we use the Magick Fields 2.
Can not create tables in a database and does not work created website. Also, can not upgrade the network.
Please fix this problem.

I hope you understand me, forgive for my English =)

Best regards
Vitaliy Kaplya
Ukraine

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
