### ISSUE TITLE
Archive navigation

### ISSUE THREAD

**Issue by maximilienborne** [magic-fields-team/Magic-Fields-2#91]
Hi,
I'm trying to put navigations link in the archive.php, where i get all my post from a particular custom type.
But when i click on the link to go to the page 2 i got this error : Apologies, but the page you requested could not be found. Perhaps searching will help.

I cant figure out, is a problem from me or from Magic Fiels 2, thank you.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
