### ISSUE TITLE
Error with new veriosn of Wordpress

### ISSUE THREAD

**Issue by Jow28** [magic-fields-team/Magic-Fields-2#97]
Hi,

I have the latest version of Wordpress installed.  When this update occured, my Magic Fields plug in quit working.  I upated to the lates verion of Magic Fields and the problem "seemed" to be fixed.  Now when I try to upload a new image to Magic Fields, I get this error:  "Sorry, your nonce did not verify".  I've been told the new version of Magic Fields doesn't work with the newer version of Wordpress.  Is this true and if not, is their a fix?

Thanks in advance.

Joanne

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
