### ISSUE TITLE
Unable to use frontend functions in ajax request

### ISSUE THREAD

**Issue by bookkey** [magic-fields-team/Magic-Fields-2#99]
In ajax registered functions (with add_action('wp_ajax_*') ) 
wordpress sets the global var 'WP_ADMIN' to true. (admin-ajax.php)
After that, the is_admin function returns this value (true).
For this reason, the plugin doesn't load the frond-end functions and
it's not possible to call any frontend functions of the plugin.

**Comment by hunk** [comment]
I'm cleaning the issues if you still have this problem reopen the issue. thanks
